/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sikiscripteditor.java;

/**
 *
 * @author Varq
 */
public class HelpNames extends javax.swing.JFrame
{

	/**
	 * Creates new form HelpNames
	 */
	public HelpNames()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        splitPane = new javax.swing.JSplitPane();
        originalNameList = new javax.swing.JList<>();
        translatedNameList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        originalNameList.setFont(new java.awt.Font("HGｺﾞｼｯｸE", 0, 18)); // NOI18N
        originalNameList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "緋月絶阿", "龍双里観", "銀狼", "出雲学人", "恵", "吾已", "比嘉総一郎", "田神梅千代", "竹千代", "平賀文吾", "梅松", "国松", "竹松", "駒内景緒", "桜坂幸運", "茂作", "曳田不動", "二重松", "毒島髑髏兵衛", "愛餓男", "亜細亜", "壱智村信咲", "壱智村香奈伊", "塚森瑞鶴", "塚森倉之助", "三田村行脚", "岡田呉羽", "岸部独眼流", "遊侠勝機", "遊侠厳顔", "川上空也", "須藤健之助", "万平太", "西中練", "牙氷", "姫喜円琥", "倉井五平", "二条両角", "那由詫", "喜質勘", "楽宗流", "我忘丸", "貞元理解", "貞元", "志波尚", "疎野紫闇", "経詠", "試金石", "吉原搾取", "大場遼太郎", "片山真", "新井瞬平", "松田禍災", "松田妖怪", "逆活", "フェイルバー・ロウペ", "キエマ・ブラック", "ギヤマン", "サニ", "リーチェル・ディッヒ" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        originalNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                originalNameListValueChanged(evt);
            }
        });
        splitPane.setLeftComponent(originalNameList);

        translatedNameList.setFont(new java.awt.Font("HGｺﾞｼｯｸE", 0, 18)); // NOI18N
        translatedNameList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "HIZUKI ZETSUA", "RYUUSOU SATOMI", "GINROU", "IZUMO GAKUTO", "MEGUMI", "AKO", "HIGA SOUICHIROU", "TAGAMI UMECHIYO", "TAKECHIYO", "HIRAGA BUNGO", "UMEMATSU", "KUNIMATSU", "TAKEMATSU", "KOMAUCHI KEIO", "SAKURAZAKA KOUUN", "MOSAKU", "HIKITA FUDOU", "NIJYUUMATSU", "BUSUJIMA DOKUROBEE", "AI UEO", "AJIA", "ICHIMURA SHINSHYOU", "ICHIMURA KANAI", "TSUKAMORI ZUIKAKU", "TSUKAMORI KURANOSOKE", "MITAMURA ANGYA", "OKADA KUREHA", "KISHIBE DOKUGANRYUU", "YUUKYOU SYOUKI", "YUUKYOU GENGAN", "KAWAKAMI KUUYA", "SUDOU KENNOSUKE", "MANPEITA", "SAICHUU REN", "GAHYOU", "KIKI ENKU", "KURAI GOHEI", "NIJYOU RYOUKAKU", "NAYUTA", "SASHICHI KAN", "RAKU ZOURU", "GABOUMARU", "SADAMOTO RIKAI", "SADAMOTO", "SHIBA SHYOU", "SONO SHIAN", "GYOUEI", "SHIKINSEKI", "YOSHIHARA SAKUSHYU", "OOBA RYOUTAROU", "KATAYAMA MAKOTO", "ARAI SHYUNPEI", "MATSUDA KASAI", "MATSUDA YOUKAI", "SAKAIKI", "FEIRUBAA ROUPE", "KIEMA BURAKKU", "GIYAMAN", "SANI", "RIICHERU DI-HI" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        translatedNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                translatedNameListValueChanged(evt);
            }
        });
        splitPane.setRightComponent(translatedNameList);

        scrollPane.setViewportView(splitPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void originalNameListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_originalNameListValueChanged
    {//GEN-HEADEREND:event_originalNameListValueChanged
        if(translatedNameList.getSelectedIndex() != originalNameList.getSelectedIndex())
			translatedNameList.setSelectedIndex(originalNameList.getSelectedIndex());
    }//GEN-LAST:event_originalNameListValueChanged

    private void translatedNameListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_translatedNameListValueChanged
    {//GEN-HEADEREND:event_translatedNameListValueChanged
        if(translatedNameList.getSelectedIndex() != originalNameList.getSelectedIndex())
			originalNameList.setSelectedIndex(translatedNameList.getSelectedIndex());
    }//GEN-LAST:event_translatedNameListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> originalNameList;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JList<String> translatedNameList;
    // End of variables declaration//GEN-END:variables
}
